### PR TITLE
Fix Nomad timeout issues

### LINKED ISSUE #227: Network fails to start: Ganache timeout
When starting vegacapsule the network fails to start with the following error. This is stopping users from using the capsule.

```
2022/08/16 15:47:55 generating network success
2022/08/16 15:47:55 starting network
2022/08/16 15:47:59 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 15:48:03 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 15:48:07 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 15:48:11 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 15:48:15 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 15:48:19 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 15:48:23 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 15:48:27 Job  "ganache-1" has timed out output: Task: "logger", State: "running", Events: "Received: Task received by client -> Task Setup: Building Task Directory -> Started: Task started by client"
2022/08/16 15:48:27 Job  "ganache-1" has timed out output: Task: "ganache-1", State: "pending", Events: "Received: Task received by client -> Task Setup: Building Task Directory -> Driver: Downloading image"
2022/08/16 15:48:27 Stopped Job: ganache-1 - 6bc76988-4489-5c40-0a6c-eabc8f3e7c64
Error: failed to start network: failed to start nomad network: failed to run pre start jobs: failed to wait for docker jobs: failed to run pre start job "ganache-1": failed to tell of job timed out: failed to run ganache-1 job: starting deadline has been exceeded
```

### LINKED ISSUE #234: failed to run testnet-nodeset-full-2-full job: starting deadline has been exceeded
cant bootstrap the network

running following cmd using system test develop config

./vegacapsule network bootstrap --config-path /Users/paulwebb/repos/system-tests/vegacapsule/capsule_config.hcl
```
Error: failed to parse config file: failed to validate config: failed to set absolute paths: failed to get absolute path for "./vega": failed to look up path for "./vega": exec: "./vega": stat ./vega: no such file or directory
```

tried 
vegacapsule network destroy
docker pull vegaprotocol/ganache:latest

the makefile option to make vegacapsule-statrt-network returns...
```
testnet-nodeset-validators-0-validator - 33b95cc3-2d24-bde2-95bb-9bfbf7fe0623
Error: failed to start network: failed to start nomad network: failed to start vega network: failed to run node sets: failed to wait for node sets: failed to run testnet-nodeset-full-2-full job: Cancelled because job is stopped
```

### PR DESCRIPTION
**Pull request by karlem**
Close #234 
Close #227

### CODE REVIEW

File: nomad/client_allocs.go [hunk 1]
```diff
@@ -11,8 +11,8 @@ import (
 )
 
 const (
-	downloadingImageMessage      = "Downloading image"
-	downloadingArtifactsMessage  = "downloading Artifacts"
+	downloadingImageMessage      = "downloading image"
+	downloadingArtifactsMessage  = "downloading artifacts"
```
Comment (vega-paul) [inline nomad/client_allocs.go:15]: artefacts

**Review by vega-paul — CHANGES_REQUESTED** [review]

File: nomad/client_allocs.go (hunk 1 above)
Comment (karlem) [reply nomad/client_allocs.go:15]: @vega-paul This is from Nomad. We have to call how they are calling it. Otherwise it won't match.

**Review by daniel1302 — APPROVED** [review]
