### PR TITLE
Network can now be stopped/started after previous start failed

### LINKED ISSUE #228: Network cannot be stopped/started after previous start failed
When the previous network is unable to start, for example, because the config is wrong, there is no option to stop the network... or start the new one.

When I update config, then call `vegacapsule network bootstrap` the network with the `--force` flag it fails with the following error:

```
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-full-0-full", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-3-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-3-validator", jobStatus: running, deploymentStatus: "cancelled", another: Cancelled due to newer version of job
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-6-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-6-validator", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-7-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-7-validator", jobStatus: running, deploymentStatus: "cancelled", another: Cancelled due to newer version of job
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-5-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-5-validator", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-4-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2022/08/16 19:39:38 Update for job: "stagnet3-nodeset-validators-4-validator", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
Error: failed to start network: failed to start nomad network: failed to start vega network: failed to run node sets: failed to wait for node sets: failed to run stagnet3-nodeset-validators-3-validator job: Cancelled due to newer version of job
Usage:
  vegacapsule network start [flags]

Flags:
      --do-not-stop-on-failure   Do not stop partially running network when failed to start
  -h, --help                     help for start

Global Flags:
      --home-path string   Specify the location of network home directory (default "/Users/daniel/.vegacapsule/testnet")
```

When I call the stop network

```
vegacapsule network stop --home-path ./home                                            <aws:vega>
2022/08/16 19:51:23 stopping network
2022/08/16 19:51:24 stopping network success
➜  vegacapsule git:(main) ✗                   
```

When I call destroy network

```
 vegacapsule network destroy --home-path ./home                                         <aws:vega>
2022/08/16 19:51:40 stopping network
2022/08/16 19:51:41 stopping network success
2022/08/16 19:51:41 network cleaning up
2022/08/16 19:51:41 network cleaning up success
```

But jobs are still in place 

image

And I am unable to start a new network. As a workaround, I have this, but it is very bad: 

```
export NOMAD_ADDR="https://n00.stagnet3.vega.xyz:4646";
export NOMAD_CACERT="./certs/nomad-ca.pem";
export NOMAD_CLIENT_CERT="./certs/client.pem";
export NOMAD_CLIENT_KEY="./certs/client-key.pem";
export NOMAD_TLS_SERVER_NAME="server.global.nomad";


nomad job status --short | grep -v Type | grep running | awk '{ print $1 }' | xargs -L 1 nomad job stop
```

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #228

### CODE REVIEW

File: cmd/network_start.go [hunk 1]
```diff
@@ -11,7 +11,7 @@ import (
 )
 
 var (
-	doNotStopOnFailure bool
+	doNotAllStopOnFailure bool
```
Comment (karlem) [inline cmd/network_start.go:14]:
```suggestion
	doNotStopAllOnFailure bool
```

File: cmd/network_start.go [hunk 2]
```diff
@@ -53,21 +53,21 @@ func netStart(ctx context.Context, state state.NetworkState) (*state.NetworkStat
 
 	nomadClient, err := nomad.NewClient(nil)
 	if err != nil {
-		return nil, fmt.Errorf("failed to create nomad client: %w", err)
+		return nil, fmt.Errorf("failed to initialize the nomad client: %w", err)
```
Comment (karlem) [inline cmd/network_start.go:56]: not sure that `the` is needed here haha

File: cmd/network_start.go [hunk 3]
```diff
@@ -53,21 +53,21 @@ func netStart(ctx context.Context, state state.NetworkState) (*state.NetworkStat
...
-	res, err := nomadRunner.StartNetwork(ctx, state.Config, state.GeneratedServices, !doNotStopOnFailure)
+	res, err := nomadRunner.StartNetwork(ctx, state.Config, state.GeneratedServices, !doNotAllStopOnFailure)
 	if err != nil {
-		return nil, fmt.Errorf("failed to start nomad network: %s", err)
+		return nil, fmt.Errorf("failed to start the network: %s", err)
 	}
 	state.RunningJobs = res
 
-	log.Println("starting network success")
+	log.Println("The network successfully started.")
```
Comment (karlem) [inline cmd/network_start.go:70]: I am honestly not sure we need `the` all over the place. It's not very important but IMHO is not needed

File: cmd/network_stop.go [hunk 4]
```diff
@@ -39,16 +39,16 @@ func init() {
 	netStopCmd.PersistentFlags().BoolVar(&stopNodesOnly,
 		"nodes-only",
 		false,
-		"Stops all nodes running in the network.",
+		"Only stops the nodes running in the network.",
```
Comment (karlem) [inline cmd/network_stop.go:42]:
```suggestion
		"Only stops running nodes sets in the network.",
```

maybe?

File: nomad/job_runner.go [hunk 5]
```diff
@@ -398,3 +341,45 @@ func (r *JobRunner) ListExposedPorts(ctx context.Context) (map[string][]int64, e
...
+
+	g, ctx := errgroup.WithContext(ctx)
+	for _, jobID := range cleanedUpJobIDs {
+		cpyJobID := jobID
+		g.Go(func() error {
+			if err := r.Client.Stop(ctx, cpyJobID, true); err != nil {
+				return fmt.Errorf("cannot stop the job %q: %w", cpyJobID, err)
+			}
+
+			log.Printf("Job %q stopped\n", cpyJobID)
```
Comment (karlem) [inline nomad/job_runner.go:370]: There is a one scenario where we don't actually want to logs this - that is when the fails during startup. It's because it would spoil some other logs so the `The jobs have been stopped.` is enough. Could you please make it optional?

**Review by karlem — APPROVED** [review]

File: cmd/network_start.go (hunk 3 above)
Comment (ValentinTrinque) [reply cmd/network_start.go:70]: Just wanted to make the log nice to read, and user friendly. But i will remove it.

File: nomad/job_runner.go (hunk 5 above)
Comment (ValentinTrinque) [reply nomad/job_runner.go:370]: I think it's valuable to trace what has been stopped. That the kind of log that was missing when we tried to understand why the stop command did nothing.

Comment (ValentinTrinque) [reply nomad/job_runner.go:370]: Are we really spoiling other logs that much ?

File: cmd/network_start.go (hunk 1 above)
Comment (ValentinTrinque) [reply cmd/network_start.go:14]: Nice catch

File: nomad/job_runner.go (hunk 5 above)
Comment (karlem) [reply nomad/job_runner.go:370]: Yes, I mean you can literally just have a variable a log it in all cases but one. Because when the network fails during the startup we literarily want to stop everything..

**Review by karlem — APPROVED** [review]
